### ISSUE TITLE
Lumen compatibility

### ISSUE THREAD

**Issue by matt-allan** [pingpong-labs/workbench#3]
Hi, I just tried to get this working with Lumen.
- The config_path call in the service providers boot method needs to be changed since that function doesn't exist in lumen.
- In WorkBenchMakeCommand, the call to `$this->laravel['path.base']` will work if it's changed to `$this->laravel->basePath()`.

After those are fixed it seems to work fine.

**Comment by gravitano** [comment]
Sorry for very late respond :D . It's done now c81cc35ce25409c83c295eea1f07da79c32e609f. Thanks!
